services:
  frontend:
    image: 0xdod/cv-challenge01-frontend
    restart: unless-stopped
    networks:
      - app_network

  backend:
    image: 0xdod/cv-challenge01-backend
    restart: unless-stopped
    networks:
      - app_network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=devopsdojo
      - POSTGRES_PASSWORD=Pssw0rd
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: "nginx:latest"
    restart: always
    depends_on:
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d:rw
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres:
    driver: local
